import { describe, it, expect } from "vitest";
import { resolve } from "path";
import { existsSync, readFileSync, mkdirSync, rmSync } from "fs";
import { loadConfig } from "../../src/compiler/load-config.js";
import { extractHandlers } from "../../src/compiler/extract-handlers.js";
import { bundleHandlers } from "../../src/compiler/bundle-handlers.js";

const FIXTURE_PATH = resolve(
  import.meta.dirname,
  "../fixtures/sample-hooks.config.ts",
);
const OUTPUT_DIR = resolve(import.meta.dirname, "../fixtures/.output-hooks");

describe("bundleHandlers", () => {
  it("compiles each handler to a self-contained JS file", async () => {
    rmSync(OUTPUT_DIR, { recursive: true, force: true });
    mkdirSync(OUTPUT_DIR, { recursive: true });

    const loaded = await loadConfig(FIXTURE_PATH);
    const handlers = extractHandlers(loaded);

    const files = await bundleHandlers({
      configPath: FIXTURE_PATH,
      handlers,
      hooksDir: OUTPUT_DIR,
    });

    expect(existsSync(resolve(OUTPUT_DIR, "runtime.cjs"))).toBe(false);
    expect(
      existsSync(resolve(OUTPUT_DIR, "preToolUse-blockDangerous.cjs")),
    ).toBe(true);
    expect(existsSync(resolve(OUTPUT_DIR, "stop-onStop.cjs"))).toBe(true);

    const handlerCode = readFileSync(
      resolve(OUTPUT_DIR, "preToolUse-blockDangerous.cjs"),
      "utf-8",
    );
    expect(handlerCode).toContain("process.stdin");
    expect(handlerCode).toContain("Generated by clauptain-hook");
    expect(handlerCode).not.toContain('require("./runtime.cjs")');

    expect(files).toHaveLength(2);
    expect(files[0].fileName).toBe("preToolUse-blockDangerous.cjs");
    expect(files[0].event).toBe("PreToolUse");

    rmSync(OUTPUT_DIR, { recursive: true, force: true });
  });
});
