import { describe, it, expect } from "vitest";
import { generateRuntime } from "../../src/compiler/runtime-template.js";

describe("generateRuntime", () => {
  it("produces valid JS with exports.run", () => {
    const code = generateRuntime();
    expect(code).toContain("exports.run");
    expect(code).toContain("process.stdin");
    expect(code).toContain("process.stdout");
    expect(code).toContain("JSON.parse");
    expect(code).toContain("process.exit(0)");
    expect(code).toContain("process.exit(2)");
  });

  it("includes the generated-by header", () => {
    const code = generateRuntime();
    expect(code).toContain("Generated by clauptain-hook");
  });

  it("produces code that can be evaluated", () => {
    const code = generateRuntime();
    expect(() => new Function(code)).not.toThrow();
  });
});
