import { describe, it, expect } from "vitest";
import { generateWrapper } from "../../src/compiler/wrapper-template.js";

describe("generateWrapper", () => {
  it("starts with sh shebang", () => {
    const code = generateWrapper("handler.cjs");
    expect(code).toMatch(/^#!\/bin\/sh\n/);
  });

  it("checks for node availability", () => {
    const code = generateWrapper("handler.cjs");
    expect(code).toContain("command -v node");
  });

  it("exits 2 with message when node is missing", () => {
    const code = generateWrapper("handler.cjs");
    expect(code).toContain("exit 2");
    expect(code).toContain("Node.js is required but not installed");
  });

  it("execs node with the correct cjs file", () => {
    const code = generateWrapper("preToolUse-blockRm.cjs");
    expect(code).toContain('exec node "$SCRIPT_DIR/preToolUse-blockRm.cjs"');
  });

  it("contains the generated-by banner", () => {
    const code = generateWrapper("handler.cjs");
    expect(code).toContain("Generated by typed-claude-hooks");
  });
});
