import * as esbuild from "esbuild";
import { chmodSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, resolve } from "path";
import { generateRuntime } from "./runtime-template.js";
import { generateWrapper } from "./wrapper-template.js";
import type { HandlerOptions } from "../types/mapping.js";
import type { HandlerEntry } from "./extract-handlers.js";

export interface BundleOptions {
  configPath: string;
  handlers: HandlerEntry[];
  hooksDir: string;
}

export interface BundledFile extends HandlerOptions {
  fileName: string;
  filePath: string;
  event: string;
  name: string;
}

function pureAnnotationPlugin(configPath: string): esbuild.Plugin {
  const absPath = resolve(configPath);
  return {
    name: "pure-define-handler",
    setup(build) {
      build.onLoad({ filter: /\.[cm]?[tj]sx?$/ }, (args) => {
        if (resolve(args.path) !== absPath) return undefined;
        const source = readFileSync(args.path, "utf8");
        const loader = args.path.endsWith(".ts") ? "ts" : "js";
        return {
          contents: source.replaceAll(
            "defineHandler(",
            "/* @__PURE__ */ defineHandler(",
          ),
          loader,
        };
      });
    },
  };
}

export async function bundleHandlers(
  options: BundleOptions,
): Promise<BundledFile[]> {
  const { configPath, handlers, hooksDir } = options;
  const absConfigPath = resolve(configPath);

  const plugin = pureAnnotationPlugin(absConfigPath);

  return await Promise.all(
    handlers.map(async (handler) => {
      const { name, event, ...options } = handler;
      const eventDir = resolve(hooksDir, event);
      mkdirSync(eventDir, { recursive: true });
      const fileName = `${name}.cjs`;
      const outfile = resolve(eventDir, fileName);

      const entryContent = [
        `import { ${name} } from ${JSON.stringify(absConfigPath)};`,
        generateRuntime(`${name}.handler`),
      ].join("\n");

      await esbuild.build({
        stdin: {
          contents: entryContent,
          resolveDir: dirname(absConfigPath),
        },
        bundle: true,
        format: "cjs",
        platform: "node",
        treeShaking: true,
        plugins: [plugin],
        outfile,
        banner: {
          js: "// Generated by typed-claude-hooks — do not edit",
        },
      });

      const wrapperFileName = fileName.replace(/\.cjs$/, ".sh");
      const wrapperOutfile = resolve(eventDir, wrapperFileName);
      writeFileSync(wrapperOutfile, generateWrapper(fileName));
      chmodSync(wrapperOutfile, 0o755);

      return { ...options, fileName, filePath: outfile, event, name };
    }),
  );
}
