import * as esbuild from "esbuild";
import { mkdirSync, rmSync, writeFileSync } from "fs";
import { resolve } from "path";
import { randomUUID } from "crypto";
import { generateRuntime } from "./runtime-template.js";
import type { HandlerOptions } from "../types/mapping.js";
import type { HandlerEntry } from "./extract-handlers.js";

export interface BundleOptions {
  configPath: string;
  handlers: HandlerEntry[];
  hooksDir: string;
}

export interface BundledFile extends HandlerOptions {
  fileName: string;
  filePath: string;
  event: string;
  name: string;
}

function toCamelCase(event: string): string {
  return event[0].toLowerCase() + event.slice(1);
}

export async function bundleHandlers(
  options: BundleOptions,
): Promise<BundledFile[]> {
  const { configPath, handlers, hooksDir } = options;
  const absConfigPath = resolve(configPath);

  mkdirSync(hooksDir, { recursive: true });

  const tmpDir = resolve(hooksDir, `.tmp-${randomUUID().slice(0, 8)}`);
  mkdirSync(tmpDir, { recursive: true });

  try {
    const results = await Promise.all(
      handlers.map(async (handler) => {
        const { name, event, handlerIndex: _, ...options } = handler;
        const fileName = `${toCamelCase(event)}-${name}.cjs`;
        const outPath = resolve(hooksDir, fileName);

        const entryContent = [
          `import { ${name} } from ${JSON.stringify(absConfigPath)};`,
          generateRuntime(`${name}.handler`),
        ].join("\n");

        const entryPath = resolve(tmpDir, `${name}.ts`);
        writeFileSync(entryPath, entryContent);

        await esbuild.build({
          entryPoints: [entryPath],
          bundle: true,
          format: "cjs",
          platform: "node",
          outfile: outPath,
          external: [],
          banner: {
            js: "// Generated by clauptain-hook — do not edit",
          },
        });

        return { ...options, fileName, filePath: outPath, event, name };
      }),
    );

    return results;
  } finally {
    rmSync(tmpDir, { recursive: true, force: true });
  }
}
